package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"ticket-system/graph/model"
	pb "ticket-system/proto"
)

// Seats is the resolver for the seats field.
func (r *queryResolver) Seats(ctx context.Context) ([]*model.Seat, error) {
	// panic(fmt.Errorf("not implemented: Seats - seats"))
	res, err := r.SeatClient.GetAvailableSeats(ctx,&pb.Empty{})
	if err!=nil{
		return nil, err
	}

	var seats[]*model.Seat

	for _,s:=range res.Seats{
		seats = append(seats, &model.Seat{
			SeatID: s.SeatId,
			Status: s.Status,
		})
	}

	return seats , nil
}

// SeatUpdated is the resolver for the seatUpdated field.
func (r *subscriptionResolver) SeatUpdated(ctx context.Context) (<-chan *model.Seat, error) {
	return r.SeatChannel, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
type mutationResolver struct{ *Resolver }
*/
