// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Seat struct {
	SeatID string `json:"seatId"`
	Status string `json:"status"`
}

type Subscription struct {
}
