// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: proto/seat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatEvent) Reset() {
	*x = SeatEvent{}
	mi := &file_proto_seat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatEvent) ProtoMessage() {}

func (x *SeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatEvent.ProtoReflect.Descriptor instead.
func (*SeatEvent) Descriptor() ([]byte, []int) {
	return file_proto_seat_proto_rawDescGZIP(), []int{0}
}

func (x *SeatEvent) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SeatEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatRequest) Reset() {
	*x = SeatRequest{}
	mi := &file_proto_seat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatRequest) ProtoMessage() {}

func (x *SeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatRequest.ProtoReflect.Descriptor instead.
func (*SeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_seat_proto_rawDescGZIP(), []int{1}
}

func (x *SeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_seat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_seat_proto_rawDescGZIP(), []int{2}
}

func (x *Seat) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Seat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SeatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=Seats,proto3" json:"Seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatList) Reset() {
	*x = SeatList{}
	mi := &file_proto_seat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatList) ProtoMessage() {}

func (x *SeatList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatList.ProtoReflect.Descriptor instead.
func (*SeatList) Descriptor() ([]byte, []int) {
	return file_proto_seat_proto_rawDescGZIP(), []int{3}
}

func (x *SeatList) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_seat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_seat_proto_rawDescGZIP(), []int{4}
}

var File_proto_seat_proto protoreflect.FileDescriptor

const file_proto_seat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/seat.proto\x12\x04seat\"S\n" +
	"\tSeatEvent\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"%\n" +
	"\vSeatRequest\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\tR\x06seatId\"N\n" +
	"\x04Seat\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\",\n" +
	"\bSeatList\x12 \n" +
	"\x05Seats\x18\x01 \x03(\v2\n" +
	".seat.SeatR\x05Seats\"\a\n" +
	"\x05Empty2\xd1\x01\n" +
	"\vSeatService\x122\n" +
	"\n" +
	"SeatStream\x12\x0f.seat.SeatEvent\x1a\x0f.seat.SeatEvent(\x010\x01\x12-\n" +
	"\vReleaseSeat\x12\x11.seat.SeatRequest\x1a\v.seat.Empty\x12-\n" +
	"\vConfirmSeat\x12\x11.seat.SeatRequest\x1a\v.seat.Empty\x120\n" +
	"\x11GetAvailableSeats\x12\v.seat.Empty\x1a\x0e.seat.SeatListB\tZ\a./protob\x06proto3"

var (
	file_proto_seat_proto_rawDescOnce sync.Once
	file_proto_seat_proto_rawDescData []byte
)

func file_proto_seat_proto_rawDescGZIP() []byte {
	file_proto_seat_proto_rawDescOnce.Do(func() {
		file_proto_seat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_seat_proto_rawDesc), len(file_proto_seat_proto_rawDesc)))
	})
	return file_proto_seat_proto_rawDescData
}

var file_proto_seat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_seat_proto_goTypes = []any{
	(*SeatEvent)(nil),   // 0: seat.SeatEvent
	(*SeatRequest)(nil), // 1: seat.SeatRequest
	(*Seat)(nil),        // 2: seat.Seat
	(*SeatList)(nil),    // 3: seat.SeatList
	(*Empty)(nil),       // 4: seat.Empty
}
var file_proto_seat_proto_depIdxs = []int32{
	2, // 0: seat.SeatList.Seats:type_name -> seat.Seat
	0, // 1: seat.SeatService.SeatStream:input_type -> seat.SeatEvent
	1, // 2: seat.SeatService.ReleaseSeat:input_type -> seat.SeatRequest
	1, // 3: seat.SeatService.ConfirmSeat:input_type -> seat.SeatRequest
	4, // 4: seat.SeatService.GetAvailableSeats:input_type -> seat.Empty
	0, // 5: seat.SeatService.SeatStream:output_type -> seat.SeatEvent
	4, // 6: seat.SeatService.ReleaseSeat:output_type -> seat.Empty
	4, // 7: seat.SeatService.ConfirmSeat:output_type -> seat.Empty
	3, // 8: seat.SeatService.GetAvailableSeats:output_type -> seat.SeatList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_seat_proto_init() }
func file_proto_seat_proto_init() {
	if File_proto_seat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_seat_proto_rawDesc), len(file_proto_seat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_seat_proto_goTypes,
		DependencyIndexes: file_proto_seat_proto_depIdxs,
		MessageInfos:      file_proto_seat_proto_msgTypes,
	}.Build()
	File_proto_seat_proto = out.File
	file_proto_seat_proto_goTypes = nil
	file_proto_seat_proto_depIdxs = nil
}
