// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc1
// source: proto/seat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatService_SeatStream_FullMethodName        = "/seat.SeatService/SeatStream"
	SeatService_ReleaseSeat_FullMethodName       = "/seat.SeatService/ReleaseSeat"
	SeatService_ConfirmSeat_FullMethodName       = "/seat.SeatService/ConfirmSeat"
	SeatService_GetAvailableSeats_FullMethodName = "/seat.SeatService/GetAvailableSeats"
)

// SeatServiceClient is the client API for SeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatServiceClient interface {
	SeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SeatEvent, SeatEvent], error)
	ReleaseSeat(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*Empty, error)
	ConfirmSeat(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*Empty, error)
	GetAvailableSeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeatList, error)
}

type seatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatServiceClient(cc grpc.ClientConnInterface) SeatServiceClient {
	return &seatServiceClient{cc}
}

func (c *seatServiceClient) SeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SeatEvent, SeatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SeatService_ServiceDesc.Streams[0], SeatService_SeatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SeatEvent, SeatEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SeatService_SeatStreamClient = grpc.BidiStreamingClient[SeatEvent, SeatEvent]

func (c *seatServiceClient) ReleaseSeat(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SeatService_ReleaseSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) ConfirmSeat(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SeatService_ConfirmSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatServiceClient) GetAvailableSeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeatList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatList)
	err := c.cc.Invoke(ctx, SeatService_GetAvailableSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeatServiceServer is the server API for SeatService service.
// All implementations must embed UnimplementedSeatServiceServer
// for forward compatibility.
type SeatServiceServer interface {
	SeatStream(grpc.BidiStreamingServer[SeatEvent, SeatEvent]) error
	ReleaseSeat(context.Context, *SeatRequest) (*Empty, error)
	ConfirmSeat(context.Context, *SeatRequest) (*Empty, error)
	GetAvailableSeats(context.Context, *Empty) (*SeatList, error)
	mustEmbedUnimplementedSeatServiceServer()
}

// UnimplementedSeatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatServiceServer struct{}

func (UnimplementedSeatServiceServer) SeatStream(grpc.BidiStreamingServer[SeatEvent, SeatEvent]) error {
	return status.Error(codes.Unimplemented, "method SeatStream not implemented")
}
func (UnimplementedSeatServiceServer) ReleaseSeat(context.Context, *SeatRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeat not implemented")
}
func (UnimplementedSeatServiceServer) ConfirmSeat(context.Context, *SeatRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSeat not implemented")
}
func (UnimplementedSeatServiceServer) GetAvailableSeats(context.Context, *Empty) (*SeatList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableSeats not implemented")
}
func (UnimplementedSeatServiceServer) mustEmbedUnimplementedSeatServiceServer() {}
func (UnimplementedSeatServiceServer) testEmbeddedByValue()                     {}

// UnsafeSeatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatServiceServer will
// result in compilation errors.
type UnsafeSeatServiceServer interface {
	mustEmbedUnimplementedSeatServiceServer()
}

func RegisterSeatServiceServer(s grpc.ServiceRegistrar, srv SeatServiceServer) {
	// If the following call panics, it indicates UnimplementedSeatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatService_ServiceDesc, srv)
}

func _SeatService_SeatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SeatServiceServer).SeatStream(&grpc.GenericServerStream[SeatEvent, SeatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SeatService_SeatStreamServer = grpc.BidiStreamingServer[SeatEvent, SeatEvent]

func _SeatService_ReleaseSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).ReleaseSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_ReleaseSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).ReleaseSeat(ctx, req.(*SeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_ConfirmSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).ConfirmSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_ConfirmSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).ConfirmSeat(ctx, req.(*SeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatService_GetAvailableSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatServiceServer).GetAvailableSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatService_GetAvailableSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatServiceServer).GetAvailableSeats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SeatService_ServiceDesc is the grpc.ServiceDesc for SeatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat.SeatService",
	HandlerType: (*SeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReleaseSeat",
			Handler:    _SeatService_ReleaseSeat_Handler,
		},
		{
			MethodName: "ConfirmSeat",
			Handler:    _SeatService_ConfirmSeat_Handler,
		},
		{
			MethodName: "GetAvailableSeats",
			Handler:    _SeatService_GetAvailableSeats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeatStream",
			Handler:       _SeatService_SeatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/seat.proto",
}
